import { expect, test, type Page } from '@playwright/test';
const password = 'topic-projects-account-a-password';
const otherPassword = 'topic-projects-account-b-password';
const secret = process.env.E2E_SECRET ?? 'newscraft-e2e-seed-secret';
async function login(page: Page, pass = password) {
 await page.request.post('/api/e2e/seed', { data: { secret, password: pass } });
 await page.goto('/login'); await page.getByLabel('Password', { exact: true }).fill(pass);
 await page.getByRole('button', { name: 'Sign in', exact: true }).click();
 await expect(page).toHaveURL(/\/$/);
 await expect(page.locator('.shell')).toHaveAttribute('data-ready', 'true');
}
for (const mobile of [false, true]) {
 test(`projects create rename move ungroup reload and new chat (${mobile ? 'mobile' : 'desktop'})`, async ({ page }) => {
  if (mobile) await page.setViewportSize({ width: 390, height: 844 });
  await login(page);
  await page.getByRole('button', { name: 'Toggle sidebar' }).first().click();
  await page.getByRole('link', { name: 'Projects', exact: true }).click();
  const name = `Carney ${Date.now()}`;
  await page.getByLabel('New project name').fill(name);
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  const projectUrl = page.url(); const id = projectUrl.split('/').pop()!;
  await expect(page.getByText('No conversations in this project yet.', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Rename project' }).click();
  await page.getByLabel('Project name', { exact: true }).fill(name + ' reporting');
  await page.getByRole('button', { name: 'Save name' }).click();
  await expect(page.getByRole('heading', { name: name + ' reporting', exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByRole('heading', { name: name + ' reporting', exact: true })).toBeVisible();
  const fixture = await page.request.post('/api/e2e/history-fixture', { data: { secret, password, count: 2 } });
  expect(fixture.ok()).toBeTruthy(); const { conversationId } = await fixture.json();
  await page.goto(`/c/${conversationId}`);
  const before = await (await page.request.get(`/api/conversations/${conversationId}/messages`)).json();
  await page.getByRole('link', { name: 'Move to project', exact: true }).click();
  await page.getByLabel('Project', { exact: true }).selectOption(id);
  await page.getByRole('button', { name: 'Save project' }).click();
  await expect(page).toHaveURL(projectUrl);
  await page.reload(); await expect(page.locator(`a[href="/c/${conversationId}"]`).last()).toBeVisible();
  await page.getByRole('link', { name: /Move or remove/ }).click();
  await page.getByLabel('Project', { exact: true }).selectOption('');
  await page.getByRole('button', { name: 'Save project' }).click();
  await expect(page).toHaveURL(new RegExp(`/c/${conversationId}$`));
  expect(await (await page.request.get(`/api/conversations/${conversationId}/messages`)).json()).toEqual(before);
  await page.goto(projectUrl);
  await expect(page.getByText('No conversations in this project yet.', { exact: false })).toBeVisible();
  const composer = page.getByLabel('Message NewsCraft');
  await expect(composer).toHaveAttribute('data-ready', 'true');
  await composer.fill('Latest news about Carney');
  // Prevent a real agent call. Membership and page navigation use real local APIs.
  let durableConversationId = '';
  await page.route('**/api/chat/runs', async route => {
   const body = route.request().postDataJSON(); durableConversationId = body.conversation_id;
   const persisted = await page.request.post('/api/e2e/seed-conversation', { data: { secret, password, conversationId: durableConversationId, userMessage: body.content, assistantMessage: 'Project durable fixture answer.' } });
   expect(persisted.ok()).toBeTruthy();
   const snapshot = { run_id:'project-fixture-run', conversation_id:durableConversationId, assistant_message_id:'project-fixture-answer', cursor:1, status:'complete', state:'complete', answerText:'Project durable fixture answer.', sources:[], citations:[], tools:[], errorMessage:null };
   await route.fulfill({status:200,contentType:'text/event-stream',body:`event: run.snapshot\ndata: ${JSON.stringify(snapshot)}\n\ndata: [DONE]\n\n`});
  });
  await composer.press('Enter');
  await expect(page).toHaveURL(/\/c\//);
  await expect(page.getByText('Project durable fixture answer.').first()).toBeVisible();
  const createdId = new URL(page.url()).pathname.split('/').pop()!;
  expect(durableConversationId).toBe(createdId);
  await page.reload(); await expect(page.getByText('Project durable fixture answer.').first()).toBeVisible();
  await page.goto(projectUrl); await page.reload();
  await expect(page.locator(`a[href="/c/${createdId}"]`).last()).toBeVisible();
  await expect(page.getByLabel('Message NewsCraft')).toHaveValue('');
  await page.screenshot({ path: `output/playwright/projects-${mobile ? 'mobile' : 'desktop'}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
 });
}
test('API rejects foreign accounts and malformed input; project URLs do not leak names', async ({ page, browser }) => {
 await login(page);
 const p = await (await page.request.post('/api/projects', { data: { name: 'Private project' } })).json();
 const c = await (await page.request.post('/api/conversations', { data: { projectId: p.id } })).json();
 for (const name of ['', ' '.repeat(5), 'x'.repeat(101), 17, null]) expect((await page.request.post('/api/projects', { data: { name } })).status()).toBe(400);
 const ctx = await browser.newContext(); const other = await ctx.newPage(); await login(other, otherPassword);
 expect((await other.request.patch(`/api/projects/${p.id}`, { data: { name: 'Stolen' } })).status()).toBe(404);
 expect((await other.request.post('/api/conversations', { data: { projectId: p.id } })).status()).toBe(404);
 expect((await other.request.patch(`/api/conversations/${c.id}/project`, { data: { projectId: null } })).status()).toBe(404);
 expect((await other.request.get(`/projects/${p.id}`)).status()).toBe(404);
 const list = await (await other.request.get('/api/projects')).json(); expect(list.projects).not.toEqual(expect.arrayContaining([expect.objectContaining({ id: p.id })]));
 await ctx.close();
});
test('failed create, rename and move keep input and existing membership for retry', async ({ page }) => {
 await login(page); await page.goto('/projects');
 await page.getByLabel('New project name').fill('Retained name');
 await page.route('**/api/projects', route => route.fulfill({status:503,body:'Unavailable'}));
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('Could not create');
 await expect(page.getByLabel('New project name')).toHaveValue('Retained name');
 await page.unroute('**/api/projects');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Retained name',exact:true})).toBeVisible();
 const id = new URL(page.url()).pathname.split('/').pop()!;
 await page.getByRole('button',{name:'Rename project'}).click();
 await page.getByLabel('Project name',{exact:true}).fill('Retry name');
 await page.route(`**/api/projects/${id}`, route => route.fulfill({status:503,body:'Unavailable'}));
 await page.getByRole('button',{name:'Save name'}).click();
 await expect(page.getByRole('alert')).toContainText('Could not rename');
 await expect(page.getByLabel('Project name',{exact:true})).toHaveValue('Retry name');
 await page.unroute(`**/api/projects/${id}`);
 await page.getByRole('button',{name:'Save name'}).click();
 await expect(page.getByRole('heading',{name:'Retry name',exact:true})).toBeVisible();
 const c = await (await page.request.post('/api/conversations',{data:{projectId:id}})).json();
 await page.goto(`/c/${c.id}/project`);
 await page.getByLabel('Project',{exact:true}).selectOption('');
 await page.route(`**/api/conversations/${c.id}/project`, route => route.fulfill({status:503,body:'Unavailable'}));
 await page.getByRole('button',{name:'Save project'}).click();
 await expect(page.getByRole('alert')).toContainText('Could not move');
 await page.reload(); await expect(page.getByText('Current project: Retry name')).toBeVisible();
});
test('route changes reset form state and ignore delayed membership saves', async ({ page }) => {
 await login(page);
 const p1 = await (await page.request.post('/api/projects',{data:{name:'Route one'}})).json();
 const p2 = await (await page.request.post('/api/projects',{data:{name:'Route two'}})).json();
 const c1 = await (await page.request.post('/api/conversations',{data:{projectId:p1.id}})).json();
 const c2 = await (await page.request.post('/api/conversations',{data:{projectId:p2.id}})).json();
 async function navigateLink(path: string) {
  await page.evaluate(path => { const a = document.createElement('a'); a.href=path; a.textContent='Test route navigation'; a.id='test-route-navigation'; a.style.cssText='position:fixed;top:100px;right:10px;z-index:9999;background:white'; document.body.append(a); },path);
  await page.locator('#test-route-navigation').click();
  await page.locator('#test-route-navigation').evaluate(el => el.remove());
 }
 await page.goto(`/c/${c1.id}/project`);
 await page.getByLabel('Project',{exact:true}).selectOption('');
 let release!: () => void;
 const gate = new Promise<void>(resolve => { release=resolve; });
 await page.route(`**/api/conversations/${c1.id}/project`, async route => { await gate; await route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'}); });
 await page.getByRole('button',{name:'Save project'}).click();
 await navigateLink(`/c/${c2.id}/project`);
 await expect(page.getByLabel('Project',{exact:true})).toHaveValue(p2.id);
 const response = page.waitForResponse(r => r.url().endsWith(`/api/conversations/${c1.id}/project`));
 release(); await response;
 await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
 await expect(page).toHaveURL(new RegExp(`/c/${c2.id}/project$`));
 await expect(page.getByRole('button',{name:'Save project'})).toBeEnabled();
 await page.goto(`/projects/${p1.id}`);
 await page.getByRole('button',{name:'Rename project'}).click();
 await page.getByLabel('Project name',{exact:true}).fill('Stale edit');
 await navigateLink(`/projects/${p2.id}`);
 await expect(page.getByLabel('Project name',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Rename project'}).click();
 await expect(page.getByLabel('Project name',{exact:true})).toHaveValue('Route two');
});
